export default defineEventHandler(async () => {
  return [
    {
      id: 0,
      name: 'بازطراحی وب‌سایت',
      customer: 'بلیک و مورتیمر',
      duration: '۳ ماه',
      picture: '/img/photos/abstracts/1.png',
      industry: 'بررسی منابع انسانی',
      status: 'در حال تکمیل',
      team: [
        {
          id: 0,
          picture: '/img/avatars/25.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 1,
          picture: undefined,
          initials: 'JP',
          color: 'info',
        },
        {
          id: 2,
          picture: '/images/avatars/11.svg',
          initials: 'EK',
          color: 'h-purple',
        },
        {
          id: 3,
          picture: '/img/avatars/5.svg',
          initials: 'ML',
          color: 'danger',
        },
        {
          id: 4,
          picture: undefined,
          initials: 'SC',
          color: 'success',
        },
      ],
    },
    {
      id: 1,
      name: 'بازطراحی اپلیکیشن موبایل',
      customer: 'پولوس هرمانوس',
      duration: '۲ ماه',
      picture: '/img/photos/abstracts/2.png',
      industry: 'غذا',
      status: 'در حال تکمیل',
      team: [
        {
          id: 148,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 2,
      name: 'توسعه راه‌حل ERP',
      customer: 'بهترین مارت',
      duration: '۶ ماه',
      picture: '/img/photos/abstracts/3.png',
      industry: 'توزیع',
      status: 'مکث',
      team: [
        {
          id: 127,
          picture: undefined,
          initials: 'BT',
          color: 'success',
        },
        {
          id: 7,
          picture: '/img/avatars/7.svg',
          initials: 'AC',
          color: 'h-purple',
        },
        {
          id: 19,
          picture: '/img/avatars/19.svg',
          initials: 'GK',
          color: 'h-yellow',
        },
        {
          id: 148,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 149,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 150,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 3,
      name: 'مدرک مفهوم وب‌سایت',
      customer: 'لس فراگروس',
      duration: '۱ ماه',
      picture: '/img/photos/abstracts/4.png',
      industry: 'لباس',
      status: 'در حال تکمیل',
      team: [
        {
          id: 188,
          picture: undefined,
          initials: 'BT',
          color: 'success',
        },
        {
          id: 187,
          picture: undefined,
          initials: 'AT',
          color: 'h-yellow',
        },
        {
          id: 5,
          picture: '/img/avatars/5.svg',
          initials: 'ML',
          color: 'warning',
        },
      ],
    },
    {
      id: 4,
      name: 'افزودن یک ماژول حسابداری',
      customer: 'نیروی کار',
      duration: '۳ هفته',
      picture: '/img/photos/abstracts/5.png',
      industry: 'نرم‌افزار',
      status: 'در حال تکمیل',
      team: [
        {
          id: 18,
          picture: '/img/avatars/18.svg',
          initials: 'EC',
          color: 'info',
        },
      ],
    },
    {
      id: 5,
      name: 'اکتشاف UX جدید',
      customer: 'نیروی کار',
      duration: '۳ هفته',
      picture: '/img/photos/abstracts/6.png',
      industry: 'نرم‌افزار',
      status: 'در حال تکمیل',
      team: [
        {
          id: 0,
          picture: '/img/avatars/25.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 14,
          picture: '/img/avatars/11.svg',
          initials: 'KL',
          color: 'danger',
        },
        {
          id: 17,
          picture: '/img/avatars/5.svg',
          initials: 'ML',
          color: 'warning',
        },
        {
          id: 150,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 151,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 152,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 154,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 6,
      name: 'توسعه اپلیکیشن سفارش‌دهی',
      customer: 'موارد خود را پیدا کنید',
      duration: '۵ ماه',
      picture: '/img/photos/abstracts/7.png',
      industry: 'خرده فروشی',
      status: 'در حال تکمیل',
      team: [
        {
          id: 0,
          picture: '/img/avatars/25.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 14,
          picture: undefined,
          initials: 'AT',
          color: 'h-yellow',
        },
        {
          id: 17,
          picture: '/img/avatars/5.svg',
          initials: 'ML',
          color: 'warning',
        },
        {
          id: 150,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 151,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 152,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 7,
      name: 'اپلیکیشن آموزشی برای کودکان',
      customer: 'کودکان کدنویس',
      duration: '۲ ماه',
      picture: '/img/photos/abstracts/8.png',
      industry: 'تحصیلات',
      status: 'در حال تکمیل',
      team: [
        {
          id: 0,
          picture: '/img/avatars/25.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 14,
          picture: undefined,
          initials: 'BV',
          color: 'h-purple',
        },
        {
          id: 8,
          picture: '/images/avatars/11.svg',
          initials: 'ML',
          color: 'warning',
        },
        {
          id: 150,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 151,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 8,
      name: 'پیاده‌سازی وایرفریم اپلیکیشن',
      customer: 'فریکو',
      duration: '2 هفته',
      picture: '/img/photos/abstracts/9.png',
      industry: 'خرده فروشی',
      status: 'در حال تکمیل',
      team: [
        {
          id: 25,
          picture: '/img/avatars/25.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 13,
          picture: '/img/avatars/13.svg',
          initials: 'TS',
          color: 'info',
        },
        {
          id: 17,
          picture: '/img/avatars/5.svg',
          initials: 'ML',
          color: 'warning',
        },
      ],
    },
    {
      id: 9,
      name: 'شبکه اجتماعی شرکتی',
      customer: 'پوبلیسیس',
      duration: '۵ ماه',
      picture: '/img/photos/abstracts/9.png',
      industry: 'Media',
      status: 'در حال تکمیل',
      team: [
        {
          id: 7,
          picture: '/img/avatars/7.svg',
          initials: 'AC',
          color: 'info',
        },
        {
          id: 165,
          picture: undefined,
          initials: 'JD',
          color: 'info',
        },
        {
          id: 27,
          picture: '/img/avatars/27.svg',
          initials: 'CE',
          color: 'warning',
        },
        {
          id: 150,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 151,
          picture: undefined,
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
  ]
})
