export default defineEventHandler(async (event) => {
  const query = getQuery(event)
  const perPage = parseInt((query.perPage as string) || '5', 10)
  const page = parseInt((query.page as string) || '1', 10)
  const filter = (query.filter as string) || ''
  const slug = (query.slug as string) || ''

  if (perPage >= 150) {
    // Create an artificial delay
    await new Promise(resolve => setTimeout(resolve, 1000))
  }

  const data = await getDemoData()
  const recipient = data.find(item => item.slug === slug)

  return {
    total: data.length,
    data: filterDemoData(data, filter, page, perPage),
    recipient,
  }
})

function filterDemoData(
  data: any[],
  filter: string,
  page: number,
  perPage: number,
) {
  const offset = (page - 1) * perPage
  if (!filter) {
    return data.slice(offset, offset + perPage)
  }
  const filterRe = new RegExp(filter, 'i')
  return data
    .filter((item) => {
      return [item.name, item.category].some(item => item.match(filterRe))
    })
    .slice(offset, offset + perPage)
}

async function getDemoData() {
  return Promise.resolve([
    {
      id: 1,
      type: 'company',
      name: 'ایر‌بی‌ان‌بی',
      slug: 'airbnb',
      category: 'شرکت مسکن',
      picture: '/img/logos/companies/airbnb.svg',
      email: 'hello@airbnb.com',
      status: 'فعال',
      taxId: 'TX-23413',
      phoneNumber: '+1 202-423-4313',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        '۱۲، خیابان سان استفانو، واحد ۴۳، طبقه اول',
        'لس آنجلس، کالیفرنیا ۹۱۲۳۴',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 275.31,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 112.28,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 387.14,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'چک',
        },
        {
          id: 4,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 628.12,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 153.47,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 311.13,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 251.39,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 742.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 2,
      type: 'person',
      name: 'جکی استراوس',
      slug: 'jackie-strauss',
      category: 'کارگر فریلنس',
      picture: '/img/avatars/9.svg',
      email: 'jackiestrauss@eltheme.ir',
      status: 'فعال',
      taxId: 'TX-392323',
      phoneNumber: '+1 202-555-0176',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        'خیابان ویکتوریا ۱۴۸، واحد D23، طبقه ۳',
        'نیویورک، نیویورک ۱۰۰۰۱',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'چک',
        },
        {
          id: 4,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 3,
      type: 'company',
      name: 'AT&T',
      slug: 'att',
      category: 'شرکت تلفن',
      picture: '/img/logos/companies/att.svg',
      email: 'hello@att.com',
      status: 'فعال',
      taxId: 'TX-231331',
      phoneNumber: '+1 131-424-4828',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        '۴۲، خیابان برنتمن، سوئیت ۱۲۴، طبقه ۲۷',
        'لاس وگاس، NV ۹۲۳۴۷',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'in',
          amount: 59.13,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۴ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 4,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 9,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 4,
      type: 'company',
      name: 'گیت‌لب',
      slug: 'gitlab',
      category: 'شرکت نرم‌افزاری',
      picture: '/img/logos/companies/gitlab.svg',
      email: 'contact@gitlab.com',
      status: 'inactive',
      taxId: 'TX-429932',
      phoneNumber: '+1 131-424-4828',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        'بزرگراه سن مارینا ۱۲، سوئیت U12، طبقه ۵',
        'لس آنجلس، کالیفرنیا 91482',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [],
    },
    {
      id: 5,
      type: 'company',
      name: 'آمازون',
      slug: 'amazon',
      category: 'شرکت بازرگانی',
      picture: '/img/logos/companies/amazon.svg',
      email: 'contact@amazon.com',
      status: 'فعال',
      taxId: 'TX-849283',
      phoneNumber: '+1 311-423-5231',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        'خیابان منهتن ۱۴، سوئیت ۲۳۱، طبقه ۴۵',
        'نیویورک، نیویورک ۸۴۲۹۹',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 382.38,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'in',
          amount: 16.31,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۴ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 128.28,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 4,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 31.17,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 483.19,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 76.87,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 12.47,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 59.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 9,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 131.48,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 6,
      type: 'person',
      name: 'هرمان مایر',
      slug: 'hermann-mayer',
      category: 'کارگر فریلنس',
      picture: '/img/avatars/16.svg',
      email: 'hermannm@eltheme.ir',
      status: 'فعال',
      taxId: 'TX-24231',
      phoneNumber: '+1 231-555-2431',
      language: 'انگلیسی',
      country: 'UK',
      address: ['۳۴، خیابان لرد آیرونس، آپ ۴۴، طبقه سوم، لندن، انگلستان ۳۱۳۱۱'],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'چک',
        },
        {
          id: 4,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 7,
      type: 'person',
      name: 'کلارک اسمیت',
      slug: 'clark-smith',
      category: 'کارگر فریلنس',
      picture: '/img/avatars/15.svg',
      email: 'karlsmith@eltheme.ir',
      status: 'فعال',
      taxId: 'TX-4231',
      phoneNumber: '+1 231-555-2431',
      language: 'انگلیسی',
      country: 'آلمان',
      address: ['۴۱، بلوار فریکنهاور، آپ ۱۱، طبقه اول، برلین، آلمان ۴۷۵۸۴'],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'چک',
        },
        {
          id: 4,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 8,
      type: 'person',
      name: 'آرون پترسون',
      slug: 'aaron-patterson',
      category: 'کارگر فریلنس',
      picture: '/img/avatars/14.svg',
      email: 'aaronp@eltheme.ir',
      status: 'فعال',
      taxId: 'TX-32332',
      phoneNumber: '+1 231-555-2431',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        '۳۵، خیابان رینمان، بلوک C4، طبقه دوم',
        'سن دیگو، کالیفرنیا ۹۱۳۴۲',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'چک',
        },
        {
          id: 4,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 9,
      type: 'person',
      name: 'جان کاریلو',
      slug: 'john-carillo',
      category: 'کارگر فریلنس',
      picture: '/img/avatars/1.svg',
      email: 'carilloj@eltheme.ir',
      status: 'فعال',
      taxId: 'TX-42442',
      phoneNumber: '+1 231-555-2431',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        'خیابان ۳۵، راینمان، سوئیت A2، طبقه ۱',
        'سانفرانسیسکو، کالیفرنیا ۹۱۳۴۲',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'چک',
        },
        {
          id: 4,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 10,
      type: 'person',
      name: 'کندرا ویلسون',
      slug: 'kendra-wilson',
      category: 'کارگر فریلنس',
      picture: '/img/avatars/10.svg',
      email: 'kendraw@eltheme.ir',
      status: 'فعال',
      taxId: 'TX-54422',
      phoneNumber: '+1 123-424-6244',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        '۲، جاده سن روکه، بلوک B2، سوئیت B24',
        'لس آنجلس، CA 91342',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'چک',
        },
        {
          id: 4,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 11,
      type: 'person',
      name: 'هاوارد استریم',
      slug: 'howard-streim',
      category: 'کارگر فریلنس',
      picture: '/img/avatars/20.svg',
      email: 'hstreim@gmail.com',
      status: 'inactive',
      taxId: 'TX-3234',
      phoneNumber: '+1 123-424-6244',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        '۳۴، خیابان سان امیلیانو، بلوک C3، سوئیت C56',
        'لس آنجلس، CA 91342',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [],
    },
    {
      id: 12,
      type: 'person',
      name: 'آنا لوپز',
      slug: 'anna-lopez',
      category: 'کارگر فریلنس',
      picture: '/img/avatars/21.svg',
      email: 'alopez@gmail.com',
      status: 'فعال',
      taxId: 'TX-428983',
      phoneNumber: '+1 123-424-6244',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        'خیابان ۷۶، راینمن، بلوک D2، طبقه اول',
        'سن دیگو، کالیفرنیا ۹۱۳۴۲',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 52.14,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 428.47,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 112.23,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'چک',
        },
        {
          id: 4,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 950,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 1500,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 550,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 380,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 449.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 13,
      type: 'company',
      name: 'آتلسیان',
      slug: 'atlassian',
      category: 'شرکت نرم‌افزاری',
      picture: '/img/logos/companies/atlassian.svg',
      email: 'hello@atlassian.com',
      status: 'فعال',
      taxId: 'TX-423255',
      phoneNumber: '+1 342-533-6343',
      language: 'انگلیسی',
      country: 'استرالیا',
      address: [
        'خیابان هریسون ۱۵، سوئیت ۲۳، طبقه ۷',
        'ملبورن، استرالیا ۴۲۸۳۹',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'in',
          amount: 59.13,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۴ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 4,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 6,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 7,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 8,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 9,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
      ],
    },
    {
      id: 14,
      type: 'company',
      name: 'دوشنبه',
      slug: 'monday',
      category: 'شرکت نرم‌افزاری',
      picture: '/img/logos/companies/monday.svg',
      email: 'contact@monday.com',
      status: 'فعال',
      taxId: 'TX-8763',
      phoneNumber: '+1 342-533-6343',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        '۱۵، خیابان منهاتن، واحد ۵۴، طبقه هفدهم',
        'نیویورک، نیویورک ۸۷۳۶۲',
      ],
      paymentMethod: {
        name: 'stripe',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'انتقال',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'in',
          amount: 59.13,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 3,
          date: '۴ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 4,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'انتقال',
        },
        {
          id: 5,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 6,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 7,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 8,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 9,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
      ],
    },
    {
      id: 15,
      type: 'company',
      name: 'UPS',
      slug: 'ups',
      category: 'شرکت لجستیک',
      picture: '/img/logos/companies/ups.svg',
      email: 'contact@ups.com',
      status: 'فعال',
      taxId: 'TX-762623',
      phoneNumber: '+1 143-546-4212',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        '۱۴، خیابان کلیسا، بلوک D56، طبقه سوم',
        'نیویورک، نیویورک ۸۴۲۹۹',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 382.38,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'in',
          amount: 16.31,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 3,
          date: '۴ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 128.28,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 4,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 31.17,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 5,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 483.19,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 6,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 76.87,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 7,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 12.47,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 8,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 59.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 9,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 131.48,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
      ],
    },
    {
      id: 16,
      type: 'company',
      name: 'اسپاتیفای',
      slug: 'spotify',
      category: 'شرکت نرم‌افزاری',
      picture: '/img/logos/companies/spotify.svg',
      email: 'hello@spotify.com',
      status: 'فعال',
      taxId: 'TX-422413',
      phoneNumber: '+1 276-133-5242',
      language: 'انگلیسی',
      country: 'ایالات متحده',
      address: [
        'خیابان سن سباستین 42، واحد 32، طبقه 3',
        'لس آنجلس، کالیفرنیا ۹۲۷۴۶',
      ],
      paymentMethod: {
        name: 'paypal',
      },
      transactions: [
        {
          id: 1,
          date: '۲۶ خرداد ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'در حال پردازش',
          method: 'transfer',
        },
        {
          id: 2,
          date: '۵ اردیبهشت ۱۴۰۲',
          type: 'in',
          amount: 59.13,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 3,
          date: '۴ اردیبهشت ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 4,
          date: '۲۳ فروردین ۱۴۰۲',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 5,
          date: '۲ اسفند ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 6,
          date: '۹ بهمن ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 7,
          date: '۱۵ آبان ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 8,
          date: '۲۵ مهر ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
        {
          id: 9,
          date: '11 شهریور ۱۴۰۱',
          type: 'out',
          amount: 65.99,
          account: '**** 7623',
          status: 'تکمیل شده',
          method: 'transfer',
        },
      ],
    },
  ])
}
