export default defineEventHandler(async () => {
  return [
    {
      id: 13,
      picture: '/demo/avatars/13.jpg',
      badge: '/images/icons/stacks/illustrator.svg',
      username: 'تارا اس.',
      fullName: 'تارا سوِنسون',
      initials: 'TS',
      color: 'danger',
      location: 'نیویورک، نیویورک',
      position: 'طراح UI/UX',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 37,
      },
      status: 'synced',
      team: [
        {
          id: 148,
          picture: undefined,
          name: 'بتی تی.',
          initials: 'BT',
          color: 'h-yellow',
        },
        {
          id: 18,
          picture: '/demo/avatars/18.jpg',
          name: 'استبان سی.',
          initials: 'EC',
          color: 'h-purple',
        },
        {
          id: 159,
          picture: undefined,
          name: 'جان د.',
          initials: 'JD',
          color: 'info',
        },
        {
          id: 7,
          picture: '/demo/avatars/7.jpg',
          name: 'آلیس سی.',
          initials: 'AC',
          color: 'success',
        },
      ],
    },
    {
      id: 37,
      picture: '/demo/avatars/37.jpg',
      badge: '/images/icons/flags/france.svg',
      username: 'هلموت ف.',
      fullName: 'هلموت فریتز',
      initials: 'HF',
      color: 'h-purple',
      location: 'پاریس، فرانسه',
      position: 'مدیر محصول',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 59,
      },
      status: 'overdue',
      team: [
        {
          id: 21,
          picture: '/demo/avatars/21.jpg',
          name: 'الیزابت ف.',
          initials: 'EF',
          color: 'warning',
        },
        {
          id: 189,
          picture: undefined,
          name: 'آلن تی.',
          initials: 'AT',
          color: 'success',
        },
        {
          id: 39,
          picture: '/demo/avatars/39.jpg',
          name: 'الخاندرو بی.',
          initials: 'AB',
          color: 'danger',
        },
      ],
    },
    {
      id: 25,
      picture: '/demo/avatars/25.jpg',
      badge: '/images/icons/stacks/js.svg',
      username: 'ملانی و.',
      fullName: 'ملانی والاس',
      initials: 'MW',
      color: 'success',
      location: 'سن‌دیگو، CA',
      position: 'توسعه‌دهنده وب',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 21,
      },
      status: 'synced',
      team: [
        {
          id: 21,
          picture: '/demo/avatars/21.jpg',
          name: 'الیزابت ف.',
          initials: 'EF',
          color: 'warning',
        },
        {
          id: 198,
          picture: undefined,
          name: 'سارا سی.',
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 39,
          picture: '/demo/avatars/39.jpg',
          name: 'الخاندرو بی.',
          initials: 'AB',
          color: 'danger',
        },
      ],
    },
    {
      id: 29,
      picture: '/demo/avatars/29.jpg',
      badge: '/images/icons/stacks/python.svg',
      username: 'حکیم سی.',
      fullName: 'حکیم کلامی',
      initials: 'HC',
      color: 'info',
      location: 'برلین، آلمان',
      position: 'مهندس نرم‌افزار',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 11,
      },
      status: 'synced',
      team: [
        {
          id: 28,
          picture: '/demo/avatars/28.jpg',
          name: 'ادوارد ف.',
          initials: 'EF',
          color: 'info',
        },
        {
          id: 33,
          picture: '/demo/avatars/33.jpg',
          name: 'هاروی ام.',
          initials: 'HM',
          color: 'warning',
        },
      ],
    },
    {
      id: 39,
      picture: '/demo/avatars/39.jpg',
      badge: '/images/icons/stacks/python.svg',
      username: 'الخاندرو بی.',
      fullName: 'الخاندرو باداخوز',
      initials: 'AB',
      color: 'h-purple',
      location: 'نیویورک، نیویورک',
      position: 'تحلیل‌گر کسب‌وکار',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 17,
      },
      status: 'blocked',
      team: [
        {
          id: 189,
          picture: undefined,
          name: 'آلن تی.',
          initials: 'AT',
          color: 'success',
        },
        {
          id: 23,
          picture: '/demo/avatars/23.jpg',
          name: 'ایرینا و.',
          initials: 'IV',
          color: 'danger',
        },
      ],
    },
    {
      id: 40,
      picture: '/demo/avatars/40.jpg',
      badge: '/images/icons/stacks/android.svg',
      username: 'ژان ام.',
      fullName: 'جین مارشند',
      initials: 'JM',
      color: 'info',
      location: 'پاریس، فرانسه',
      position: 'توسعه‌دهنده موبایل',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 14,
      },
      status: 'synced',
      team: [
        {
          id: 148,
          picture: undefined,
          name: 'بتی تی.',
          initials: 'BT',
          color: 'h-yellow',
        },
        {
          id: 18,
          picture: '/demo/avatars/18.jpg',
          name: 'استبان سی.',
          initials: 'EC',
          color: 'h-purple',
        },
        {
          id: 159,
          picture: undefined,
          name: 'جان د.',
          initials: 'JD',
          color: 'info',
        },
      ],
    },
    {
      id: 19,
      picture: '/demo/avatars/19.jpg',
      badge: '/images/icons/flags/germany.svg',
      username: 'گرتا ک.',
      fullName: 'گرتا کروپفر',
      initials: 'GK',
      color: 'h-yellow',
      location: 'لس‌آنجلس، کالیفرنیا',
      position: 'مدیر فروش',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 18,
      },
      status: 'synced',
      team: [
        {
          id: 198,
          picture: undefined,
          name: 'سارا سی.',
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 27,
          picture: '/demo/avatars/27.jpg',
          name: 'کارمن ای.',
          initials: 'CE',
          color: 'info',
        },
      ],
    },
    {
      id: 9,
      picture: '/demo/avatars/9.jpg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      username: 'آنا بی.',
      fullName: 'آنا بیکر',
      initials: 'AB',
      color: 'info',
      location: 'سان فرانسیسکو، کالیفرنیا',
      position: 'طراح UI/UX',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 27,
      },
      status: 'synced',
      team: [
        {
          id: 189,
          picture: undefined,
          name: 'آلن تی.',
          initials: 'AT',
          color: 'success',
        },
        {
          id: 23,
          picture: '/demo/avatars/23.jpg',
          name: 'ایرینا و.',
          initials: 'IV',
          color: 'danger',
        },
      ],
    },
    {
      id: 5,
      picture: '/demo/avatars/5.jpg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      username: 'مری ال.',
      fullName: 'مری لبوفسکی',
      initials: 'ML',
      color: 'h-yellow',
      location: 'سن‌دیگو، CA',
      position: 'مدیر پروژه',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 31,
      },
      status: 'synced',
      team: [
        {
          id: 148,
          picture: undefined,
          name: 'بتی تی.',
          initials: 'BT',
          color: 'h-yellow',
        },
        {
          id: 18,
          picture: '/demo/avatars/18.jpg',
          name: 'استبان سی.',
          initials: 'EC',
          color: 'h-purple',
        },
        {
          id: 159,
          picture: undefined,
          name: 'جان د.',
          initials: 'JD',
          color: 'info',
        },
        {
          id: 7,
          picture: '/demo/avatars/7.jpg',
          name: 'آلیس سی.',
          initials: 'AC',
          color: 'success',
        },
      ],
    },
    {
      id: 32,
      picture: '/demo/avatars/32.jpg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      username: 'جاناتان ک.',
      fullName: 'جاناتان کروگر',
      initials: 'JK',
      color: 'info',
      location: 'لس‌آنجلس، کالیفرنیا',
      position: 'مدیر محصول',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 9,
      },
      status: 'synced',
      team: [
        {
          id: 21,
          picture: '/demo/avatars/21.jpg',
          name: 'الیزابت ف.',
          initials: 'EF',
          color: 'warning',
        },
        {
          id: 198,
          picture: undefined,
          name: 'سارا سی.',
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 39,
          picture: '/demo/avatars/39.jpg',
          name: 'الخاندرو بی.',
          initials: 'AB',
          color: 'danger',
        },
      ],
    },
    {
      id: 36,
      picture: '/demo/avatars/36.jpg',
      badge: '/images/icons/flags/france.svg',
      username: 'بنوآ ل.',
      fullName: 'بنوآ لبلانک',
      initials: 'BL',
      color: 'h-purple',
      location: 'پاریس، فرانسه',
      position: 'مهندس نرم‌افزار',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 22,
      },
      status: 'synced',
      team: [
        {
          id: 148,
          picture: undefined,
          name: 'بتی تی.',
          initials: 'BT',
          color: 'h-yellow',
        },
        {
          id: 31,
          picture: '/demo/avatars/31.jpg',
          name: 'یاسین آ.',
          initials: 'YA',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 38,
      picture: '/demo/avatars/38.jpg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      username: 'کریستی د.',
      fullName: 'کریستی دالاس',
      initials: 'CD',
      color: 'info',
      location: 'لس‌آنجلس، کالیفرنیا',
      position: 'توسعه‌دهنده وب',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 43,
      },
      status: 'overdue',
      team: [
        {
          id: 33,
          picture: '/demo/avatars/33.jpg',
          name: 'هاروی ام.',
          initials: 'HM',
          color: 'warning',
        },
        {
          id: 26,
          picture: '/demo/avatars/26.jpg',
          name: 'کورتنی و.',
          initials: 'CW',
          color: 'info',
        },
      ],
    },
    {
      id: 26,
      picture: '/demo/avatars/26.jpg',
      badge: '/images/icons/flags/australia.svg',
      username: 'کورتنی و.',
      fullName: 'کورتنی ویلسون',
      initials: 'CW',
      color: 'info',
      location: 'ملبورن، استرالیا',
      position: 'توسعه‌دهنده وب',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 13,
      },
      status: 'synced',
      team: [
        {
          id: 21,
          picture: '/demo/avatars/21.jpg',
          name: 'الیزابت ف.',
          initials: 'EF',
          color: 'warning',
        },
        {
          id: 189,
          picture: undefined,
          name: 'آلن تی.',
          initials: 'AT',
          color: 'success',
        },
        {
          id: 39,
          picture: '/demo/avatars/39.jpg',
          name: 'الخاندرو بی.',
          initials: 'AB',
          color: 'danger',
        },
      ],
    },
    {
      id: 16,
      picture: '/demo/avatars/16.jpg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      username: 'جیسون ج.',
      fullName: 'جیسون گوارانک',
      initials: 'JG',
      color: 'danger',
      location: 'هیوستون، تگزاس',
      position: 'تحلیل‌گر کسب‌وکار',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 39,
      },
      status: 'synced',
      team: [
        {
          id: 14,
          picture: '/demo/avatars/14.jpg',
          name: 'رایان ب.',
          initials: 'RB',
          color: 'warning',
        },
        {
          id: 198,
          picture: undefined,
          name: 'سارا سی.',
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
    {
      id: 23,
      picture: '/demo/avatars/23.jpg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      username: 'ایرینا و.',
      fullName: 'ایرینا ویربوفسکی',
      initials: 'IV',
      color: 'info',
      location: 'سن خوزه، کالیفرنیا',
      position: 'مدیر پروژه',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 7,
      },
      status: 'synced',
      team: [
        {
          id: 189,
          picture: undefined,
          name: 'آلن تی.',
          initials: 'AT',
          color: 'success',
        },
        {
          id: 34,
          picture: '/demo/avatars/34.jpg',
          name: 'دنیل ر.',
          initials: 'DR',
          color: 'h-yellow',
        },
      ],
    },
    {
      id: 28,
      picture: '/demo/avatars/28.jpg',
      badge: '/images/icons/flags/france.svg',
      username: 'ادوارد ف.',
      fullName: 'ادوارد فالانت',
      initials: 'EF',
      color: 'success',
      location: 'پاریس، فرانسه',
      position: 'توسعه‌دهنده وب',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 19,
      },
      status: 'synced',
      team: [
        {
          id: 148,
          picture: undefined,
          name: 'بتی تی.',
          initials: 'BT',
          color: 'h-yellow',
        },
        {
          id: 18,
          picture: '/demo/avatars/18.jpg',
          name: 'استبان سی.',
          initials: 'EC',
          color: 'h-purple',
        },
        {
          id: 159,
          picture: undefined,
          name: 'جان د.',
          initials: 'JD',
          color: 'info',
        },
      ],
    },
    {
      id: 7,
      picture: '/demo/avatars/7.jpg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      username: 'آلیس سی.',
      fullName: 'آلیس کاراسکا',
      initials: 'AC',
      color: 'info',
      location: 'سن‌دیگو، CA',
      position: 'مهندس نرم‌افزار',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 14,
      },
      status: 'synced',
      team: [
        {
          id: 25,
          picture: '/demo/avatars/25.jpg',
          name: 'ملانی و.',
          initials: 'MW',
          color: 'success',
        },
        {
          id: 198,
          picture: undefined,
          name: 'سارا سی.',
          initials: 'SC',
          color: 'h-purple',
        },
        {
          id: 12,
          picture: '/demo/avatars/12.jpg',
          name: 'جاشوا اس.',
          initials: 'JS',
          color: 'warning',
        },
      ],
    },
    {
      id: 22,
      picture: '/demo/avatars/22.jpg',
      badge: '/images/icons/flags/united-states-of-america.svg',
      username: 'دواین اچ.',
      fullName: 'دوین هیکس',
      initials: 'DH',
      color: 'info',
      location: 'لس‌آنجلس، کالیفرنیا',
      position: 'مدیر محصول',
      bio: 'این یک توصیف کاربر خوب است که می‌توانیم به عنوان محتوای نمایشی استفاده کنیم.',
      tasks: {
        pending: 5,
      },
      status: 'synced',
      team: [
        {
          id: 148,
          picture: undefined,
          name: 'بتی تی.',
          initials: 'BT',
          color: 'h-yellow',
        },
        {
          id: 198,
          picture: undefined,
          name: 'سارا سی.',
          initials: 'SC',
          color: 'h-purple',
        },
      ],
    },
  ]
})
