export default defineEventHandler(async () => {
  return await getDemoData()
})

async function getDemoData() {
  return Promise.resolve([
    {
      type: 'people',
      name: 'ملانی ال.',
      subtext: 'طراح UI/UX',
      src: '/img/avatars/25.svg',
      text: 'ML',
      url: '#',
    },
    {
      type: 'people',
      name: 'کندرا و.',
      subtext: 'توسعه‌دهنده فرانت‌اند',
      src: '/img/avatars/10.svg',
      text: 'KW',
      url: '#',
    },
    {
      type: 'people',
      name: 'هرمان م.',
      subtext: 'توسعه‌دهنده بک‌اند',
      src: '/img/avatars/16.svg',
      text: 'HM',
      url: '#',
    },
    {
      type: 'project',
      name: 'اپلیکیشن تحویل',
      src: '/img/apps/1.png',
      subtext: 'پروژه طراحی وب',
      text: 'CG',
      url: '#',
    },
    {
      type: 'project',
      name: 'اپلیکیشن موبایل آموزش الکترونیک',
      src: '/img/apps/2.png',
      subtext: 'پروژه طراحی وب',
      text: 'CG',
      url: '#',
    },
    {
      type: 'people',
      name: 'گرتا ک.',
      subtext: 'توسعه‌دهنده فرانت‌اند',
      src: '/img/avatars/24.svg',
      text: 'GK',
      url: '#',
    },
    {
      type: 'people',
      name: 'مایا ر.',
      subtext: 'توسعه‌دهنده فرانت‌اند',
      src: '/img/avatars/2.svg',
      text: 'MR',
      url: '#',
    },
    {
      type: 'file',
      name: 'company-ui-ux-guide.pdf',
      src: '/img/icons/files/pdf.svg',
      subtext: 'فایل PDF',
      text: 'CG',
      url: '#',
    },
    {
      type: 'file',
      name: 'company-budget.xlsx',
      src: '/img/icons/files/sheet.svg',
      subtext: 'فایل اکسل',
      text: 'CG',
      url: '#',
    },
    {
      type: 'file',
      name: 'company-logo.ai',
      src: '/img/icons/files/ai.svg',
      subtext: 'فایل AI',
      text: 'AI',
      url: '#',
    },
    {
      type: 'project',
      name: 'داشبورد سلامت و تناسب اندام',
      src: '/img/apps/3.png',
      subtext: 'پروژه وب اپ',
      text: 'HF',
      url: '#',
    },
    {
      type: 'project',
      name: 'طراحی وب‌اپ HR',
      src: '/img/apps/4.png',
      subtext: 'پروژه طراحی وب',
      text: 'HR',
      url: '#',
    },
    {
      type: 'people',
      name: 'هاوارد سی.',
      subtext: 'معمار راه‌حل',
      src: '/img/avatars/20.svg',
      text: 'HC',
      url: '#',
    },
    {
      type: 'people',
      name: 'کلارک گ.',
      subtext: 'توسعه‌دهنده فول استک',
      src: '/img/avatars/3.svg',
      text: 'CG',
      url: '#',
    },
  ])
}
